#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

ogap=30
igap=30

white="#FFFFFF"
whitish="#AAAAAA"
black="#000000"
magenta="#ca1444"
pink="#ec3f97"

bspc config border_width         5
bspc config window_gap           $igap
bspc config top_padding          $ogap
bspc config left_padding         $ogap
bspc config right_padding        $ogap
bspc config bottom_padding       $ogap

bspc config normal_border_color  $whitish
bspc config focused_border_color $white

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


#start programs
xrandr --newmode "1920x1080_60.00"  172.80  1920 2040 2248 2576  1080 1081 1084 1118  -HSync +Vsync
xrandr --addmode Virtual-1 "1920x1080_60.00"
xrandr --output Virtual-1 --mode "1920x1080_60.00"

feh --bg-center ~/pics/wallpaper
#compton -b --config ~/.config/compton/compton.conf

#rofi -show run
